name: "Test Auth0 Passwordless Action"
description: "Tests Auth0 Passwordless Action"

runs:
  using: "composite"
  steps:
    - name: Lint
      shell: bash
      run: pnpm lint:check

    - name: Format
      shell: bash
      run: pnpm format:check

    - name: Run tests
      shell: bash
      run: pnpm test
