name: Build

on: [push]

jobs:

  # This job runs tests for Auth0 PassKey policy
  passwordless:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Specify your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./
